name: Laravel

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  composer:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
    
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.1'

    - name: Install Dependencies
      run: composer install -q --ignore-platform-reqs --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Install Dependencies
      run: composer update


    - name: Composer Cache Directory
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-composerx-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-composerx-


      
  laravel-tests:
    runs-on: ubuntu-latest
    needs: [composer]
    steps:
    
    - uses: actions/checkout@v2
    
    - name: Get Composer Cache Directory
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-composerx-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-composerx-

    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.1'
    
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"   
    
    - name: Copy .env
      run: php artisan key:generate   
    
    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.sqlite
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: vendor/bin/phpunit


  deploy_production:
    runs-on: ubuntu-latest
    needs: [composer, laravel-tests]
    steps:
    
    - uses: actions/checkout@v2
    
    - name: Get Composer Cache Directory
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-composerx-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-composerx-
          
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.YOURAPP_SSH_KEY }}
        name: id_rsa # optional
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
        config: |
          Host lrvlsauce
            HostName 94.126.16.46
            Port 2121
            User lrvlsauce
        if_key_exists: replace # replace / ignore / fail; optional (defaults to fail)
        
    - name: Adding Known Hosts
      run: ssh-keyscan -p 2121 -H ${{ secrets.KNOWN_HOSTS }} >> ~/.ssh/known_hosts
      
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.1'
    - name: php version
      run: php --version
    - name: Envoy goooo
      run: vendor/bin/envoy run deploy
